import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '../.env') });
import fs from 'fs';
import { searchTrends } from './lib/researcher.js';
import { brainstormIdeas } from './lib/brainstormer.js';

async function runAgent() {
    console.log('🚀 Starting VYRE.DK Agent Manager...');

    // 1. Research
    const researchData = await searchTrends();

    // 2. Brainstorm
    const reportContent = await brainstormIdeas(researchData);

    // 3. Save Report
    const date = new Date().toISOString().split('T')[0];
    const reportDir = path.join(__dirname, 'reports');

    if (!fs.existsSync(reportDir)) {
        fs.mkdirSync(reportDir);
    }

    const filename = `report-${date}.md`;
    const filePath = path.join(reportDir, filename);

    const fullContent = `
# 🕵️ Agent Report: ${date}

${reportContent}

---
*Generated by VYRE Agent Manager*
  `;

    fs.writeFileSync(filePath, fullContent);
    console.log(`✅ Report saved to: ${filePath}`);
}

runAgent();
