import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { brainstormIdeas } from './lib/brainstormer.js';
import fs from 'fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '../.env') });

// Data provided by the user (truncated for brevity/token limits)
const userProvidedData = {
    query: "Hero-product-webshop inspiration",
    results: [
        {
            title: "Mariana Squarespace Template Review - JPK Design Co",
            url: "https://www.jpkdesignco.com/blog/mariana-squarespace-template-review",
            content: "Hero section with large image and headline ('Meet our new limited collection'), product grid showing three products with images, prices, size dropdowns, quantity selectors, and 'Add to cart' buttons... The aesthetic is bold and editorial."
        },
        {
            title: "Ecommerce in Germany 2025: Market Guide",
            url: "https://www.netguru.com/blog/ecommerce-market-germany",
            content: "Key trends include mobile commerce, sustainability, and second-hand market expansion. German consumers value transparency, trust, and convenience."
        },
        {
            title: "Muzli.Me - Your Creative Identity",
            url: "https://me.muz.li/",
            content: "Showcases various design inspirations: 'CUTEFOLD – metal furnishing accessories', 'Fonts That Never Fail', 'Cosmic Thanksgiving Party Flyer'. Highlighting bold visuals and creative identities."
        }
    ]
};

// Adapt to the format expected by brainstormer.js
const researchData = [
    {
        query: userProvidedData.query,
        findings: userProvidedData.results
    }
];

async function runTest() {
    console.log('🧪 Running Agent with User Data (Gemini Edition)...');

    const reportContent = await brainstormIdeas(researchData);

    const date = new Date().toISOString().split('T')[0];
    const filePath = path.join(__dirname, 'reports', `report-manual-gemini-${date}.md`);

    const fullContent = `
# 🧪 Manual Test Report: ${date}

**Input Source**: User Provided Data ("Hero-product-webshop inspiration")
**Model**: Google Gemini 1.5 Flash

${reportContent}

---
*Generated by VYRE Agent Manager (Test Run)*
  `;

    fs.writeFileSync(filePath, fullContent);
    console.log(`✅ Test Report saved to: ${filePath}`);
}

runTest();
